[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = -DCORE_DEBUG_LEVEL=2
lib_deps =
    gin66/FastAccelStepper @ ^0.31.5
    bblanchon/ArduinoJson @ ^7.0.4
